# -*- coding: utf-8 -*-
"""AI_A03_k232001.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1taO4uKiMBXmQkJVl2XsXwdgJkPARLS2u

AI Assignment03 - k232001  
Kaggle Playground Series S6E4
"""

!pip install -q catboost

import pandas as pd
import numpy as np

from google.colab import files

from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

from sklearn.preprocessing import LabelEncoder

from sklearn.tree import DecisionTreeClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.linear_model import LogisticRegression

from catboost import CatBoostClassifier

train = pd.read_csv("train.csv")
test = pd.read_csv("test.csv")

print("Train Shape:", train.shape)
print("Test Shape :", test.shape)

train.head()

target = "Irrigation_Need"

X = train.drop(columns=[target])
y = train[target]

# Save IDs
test_ids = test["id"]

# Combine for encoding consistency
combined = pd.concat([X, test], axis=0)

# Encode object columns
encoders = {}

for col in combined.columns:
    if combined[col].dtype == "object":
        le = LabelEncoder()
        combined[col] = le.fit_transform(combined[col].astype(str))
        encoders[col] = le

# Split back
X = combined.iloc[:len(train), :]
X_test = combined.iloc[len(train):, :]

# Encode target
target_encoder = LabelEncoder()
y_encoded = target_encoder.fit_transform(y)

X_train, X_val, y_train, y_val = train_test_split(
    X, y_encoded,
    test_size=0.2,
    random_state=42,
    stratify=y_encoded
)

results = {}

# Decision Tree
dt = DecisionTreeClassifier(max_depth=12, random_state=42)
dt.fit(X_train, y_train)
pred = dt.predict(X_val)
acc = accuracy_score(y_val, pred)
results["Decision Tree"] = acc
print("Decision Tree Accuracy:", acc)

# Naive Bayes
nb = GaussianNB()
nb.fit(X_train, y_train)
pred = nb.predict(X_val)
acc = accuracy_score(y_val, pred)
results["Naive Bayes"] = acc
print("Naive Bayes Accuracy:", acc)

# CatBoost
cb = CatBoostClassifier(
    iterations=150,
    depth=6,
    learning_rate=0.1,
    loss_function='MultiClass',
    verbose=0
)

cb.fit(X_train, y_train)
pred = cb.predict(X_val).astype(int).flatten()
acc = accuracy_score(y_val, pred)
results["CatBoost"] = acc
print("CatBoost Accuracy:", acc)

print("\nMODEL RESULTS")
for k,v in results.items():
    print(k, ":", round(v,4))

best_model_name = max(results, key=results.get)
print("\nBest Model =", best_model_name)

from sklearn.metrics import ConfusionMatrixDisplay
import matplotlib.pyplot as plt

pred = cb.predict(X_val).astype(int).flatten()

cm = confusion_matrix(y_val, pred)

disp = ConfusionMatrixDisplay(cm)
disp.plot()
plt.show()

final_model = CatBoostClassifier(
    iterations=300,
    depth=8,
    learning_rate=0.08,
    loss_function='MultiClass',
    verbose=100
)

final_model.fit(X, y_encoded)

final_preds = final_model.predict(X_test).astype(int).flatten()

final_labels = target_encoder.inverse_transform(final_preds)

submission = pd.DataFrame({
    "id": test_ids,
    "Irrigation_Need": final_labels
})

submission.to_csv("submission.csv", index=False)

print("submission.csv created!")

files.download("submission.csv")